
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Banner': typeof import("../components/global/banner.vue")['default']
    'CardsCardShow': typeof import("../components/Cards/cardShow.vue")['default']
    'CardsCardShowTvs': typeof import("../components/Cards/cardShowTvs.vue")['default']
    'HomeMovieCardsDetails': typeof import("../components/HomeMovie/CardsDetails.vue")['default']
    'HomeMovieTopHeader': typeof import("../components/HomeMovie/TopHeader.vue")['default']
    'HomeMovie': typeof import("../components/HomeMovie/movie.vue")['default']
    'SearchAllSearchs': typeof import("../components/Search/allSearchs.vue")['default']
    'ThemeChangeTheme': typeof import("../components/Theme/changeTheme.vue")['default']
    'ToastFaield': typeof import("../components/Toast/toastFaield.vue")['default']
    'ToastSuccess': typeof import("../components/Toast/toastSuccess.vue")['default']
    'TvShowTvshow': typeof import("../components/TvShow/Tvshow.vue")['default']
    'AuthLogin': typeof import("../components/auth/Login.vue")['default']
    'AuthRegister': typeof import("../components/auth/Register.vue")['default']
    'Avatar': typeof import("../components/avatar/avatar.vue")['default']
    'ButtonsCardButtons': typeof import("../components/buttonsCard/buttons.vue")['default']
    'CardloadinHomeCardLoading': typeof import("../components/cardloadinHome/cardLoading.vue")['default']
    'ImageSwiperImages': typeof import("../components/imageSwiper/images.vue")['default']
    'LangDropDown': typeof import("../components/lang/DropDown.vue")['default']
    'LayoutAuthHeaderNav': typeof import("../components/layout/auth/headerNav.vue")['default']
    'LayoutNavBar': typeof import("../components/layout/navBar.vue")['default']
    'LayoutSideBar': typeof import("../components/layout/sideBar.vue")['default']
    'ModalSearch': typeof import("../components/modalSearch/search.vue")['default']
    'ModalSearchNav': typeof import("../components/modalSearch/searchNav.vue")['default']
    'VideoModal': typeof import("../components/videoModal/videoModal.vue")['default']
    'VideoModalForCardsVideoModal': typeof import("../components/videoModalForCards/videoModal.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'AutoComplete': typeof import("primevue/autocomplete")['default']
    'Calendar': typeof import("primevue/calendar")['default']
    'CascadeSelect': typeof import("primevue/cascadeselect")['default']
    'Checkbox': typeof import("primevue/checkbox")['default']
    'Chips': typeof import("primevue/chips")['default']
    'ColorPicker': typeof import("primevue/colorpicker")['default']
    'Dropdown': typeof import("primevue/dropdown")['default']
    'FloatLabel': typeof import("primevue/floatlabel")['default']
    'IconField': typeof import("primevue/iconfield")['default']
    'InputGroup': typeof import("primevue/inputgroup")['default']
    'InputGroupAddon': typeof import("primevue/inputgroupaddon")['default']
    'InputIcon': typeof import("primevue/inputicon")['default']
    'InputMask': typeof import("primevue/inputmask")['default']
    'InputNumber': typeof import("primevue/inputnumber")['default']
    'InputOtp': typeof import("primevue/inputotp")['default']
    'InputSwitch': typeof import("primevue/inputswitch")['default']
    'InputText': typeof import("primevue/inputtext")['default']
    'Knob': typeof import("primevue/knob")['default']
    'Listbox': typeof import("primevue/listbox")['default']
    'MultiSelect': typeof import("primevue/multiselect")['default']
    'Password': typeof import("primevue/password")['default']
    'RadioButton': typeof import("primevue/radiobutton")['default']
    'Rating': typeof import("primevue/rating")['default']
    'SelectButton': typeof import("primevue/selectbutton")['default']
    'Slider': typeof import("primevue/slider")['default']
    'Textarea': typeof import("primevue/textarea")['default']
    'ToggleButton': typeof import("primevue/togglebutton")['default']
    'TreeSelect': typeof import("primevue/treeselect")['default']
    'TriStateCheckbox': typeof import("primevue/tristatecheckbox")['default']
    'Button': typeof import("primevue/button")['default']
    'ButtonGroup': typeof import("primevue/buttongroup")['default']
    'SpeedDial': typeof import("primevue/speeddial")['default']
    'SplitButton': typeof import("primevue/splitbutton")['default']
    'Column': typeof import("primevue/column")['default']
    'Row': typeof import("primevue/row")['default']
    'ColumnGroup': typeof import("primevue/columngroup")['default']
    'DataTable': typeof import("primevue/datatable")['default']
    'DataView': typeof import("primevue/dataview")['default']
    'DataViewLayoutOptions': typeof import("primevue/dataviewlayoutoptions")['default']
    'OrderList': typeof import("primevue/orderlist")['default']
    'OrganizationChart': typeof import("primevue/organizationchart")['default']
    'Paginator': typeof import("primevue/paginator")['default']
    'PickList': typeof import("primevue/picklist")['default']
    'Tree': typeof import("primevue/tree")['default']
    'TreeTable': typeof import("primevue/treetable")['default']
    'Timeline': typeof import("primevue/timeline")['default']
    'VirtualScroller': typeof import("primevue/virtualscroller")['default']
    'Accordion': typeof import("primevue/accordion")['default']
    'AccordionTab': typeof import("primevue/accordiontab")['default']
    'Card': typeof import("primevue/card")['default']
    'DeferredContent': typeof import("primevue/deferredcontent")['default']
    'Divider': typeof import("primevue/divider")['default']
    'Fieldset': typeof import("primevue/fieldset")['default']
    'Panel': typeof import("primevue/panel")['default']
    'ScrollPanel': typeof import("primevue/scrollpanel")['default']
    'Splitter': typeof import("primevue/splitter")['default']
    'SplitterPanel': typeof import("primevue/splitterpanel")['default']
    'Stepper': typeof import("primevue/stepper")['default']
    'StepperPanel': typeof import("primevue/stepperpanel")['default']
    'TabView': typeof import("primevue/tabview")['default']
    'TabPanel': typeof import("primevue/tabpanel")['default']
    'Toolbar': typeof import("primevue/toolbar")['default']
    'ConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'ConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'Dialog': typeof import("primevue/dialog")['default']
    'DynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'OverlayPanel': typeof import("primevue/overlaypanel")['default']
    'Sidebar': typeof import("primevue/sidebar")['default']
    'FileUpload': typeof import("primevue/fileupload")['default']
    'Breadcrumb': typeof import("primevue/breadcrumb")['default']
    'ContextMenu': typeof import("primevue/contextmenu")['default']
    'Dock': typeof import("primevue/dock")['default']
    'Menu': typeof import("primevue/menu")['default']
    'Menubar': typeof import("primevue/menubar")['default']
    'MegaMenu': typeof import("primevue/megamenu")['default']
    'PanelMenu': typeof import("primevue/panelmenu")['default']
    'Steps': typeof import("primevue/steps")['default']
    'TabMenu': typeof import("primevue/tabmenu")['default']
    'TieredMenu': typeof import("primevue/tieredmenu")['default']
    'Message': typeof import("primevue/message")['default']
    'InlineMessage': typeof import("primevue/inlinemessage")['default']
    'Toast': typeof import("primevue/toast")['default']
    'Carousel': typeof import("primevue/carousel")['default']
    'Galleria': typeof import("primevue/galleria")['default']
    'Image': typeof import("primevue/image")['default']
    'AvatarGroup': typeof import("primevue/avatargroup")['default']
    'Badge': typeof import("primevue/badge")['default']
    'BlockUI': typeof import("primevue/blockui")['default']
    'Chip': typeof import("primevue/chip")['default']
    'Inplace': typeof import("primevue/inplace")['default']
    'MeterGroup': typeof import("primevue/metergroup")['default']
    'ScrollTop': typeof import("primevue/scrolltop")['default']
    'Skeleton': typeof import("primevue/skeleton")['default']
    'ProgressBar': typeof import("primevue/progressbar")['default']
    'ProgressSpinner': typeof import("primevue/progressspinner")['default']
    'Tag': typeof import("primevue/tag")['default']
    'Terminal': typeof import("primevue/terminal")['default']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBanner': typeof import("../components/global/banner.vue")['default']
    'LazyCardsCardShow': typeof import("../components/Cards/cardShow.vue")['default']
    'LazyCardsCardShowTvs': typeof import("../components/Cards/cardShowTvs.vue")['default']
    'LazyHomeMovieCardsDetails': typeof import("../components/HomeMovie/CardsDetails.vue")['default']
    'LazyHomeMovieTopHeader': typeof import("../components/HomeMovie/TopHeader.vue")['default']
    'LazyHomeMovie': typeof import("../components/HomeMovie/movie.vue")['default']
    'LazySearchAllSearchs': typeof import("../components/Search/allSearchs.vue")['default']
    'LazyThemeChangeTheme': typeof import("../components/Theme/changeTheme.vue")['default']
    'LazyToastFaield': typeof import("../components/Toast/toastFaield.vue")['default']
    'LazyToastSuccess': typeof import("../components/Toast/toastSuccess.vue")['default']
    'LazyTvShowTvshow': typeof import("../components/TvShow/Tvshow.vue")['default']
    'LazyAuthLogin': typeof import("../components/auth/Login.vue")['default']
    'LazyAuthRegister': typeof import("../components/auth/Register.vue")['default']
    'LazyAvatar': typeof import("../components/avatar/avatar.vue")['default']
    'LazyButtonsCardButtons': typeof import("../components/buttonsCard/buttons.vue")['default']
    'LazyCardloadinHomeCardLoading': typeof import("../components/cardloadinHome/cardLoading.vue")['default']
    'LazyImageSwiperImages': typeof import("../components/imageSwiper/images.vue")['default']
    'LazyLangDropDown': typeof import("../components/lang/DropDown.vue")['default']
    'LazyLayoutAuthHeaderNav': typeof import("../components/layout/auth/headerNav.vue")['default']
    'LazyLayoutNavBar': typeof import("../components/layout/navBar.vue")['default']
    'LazyLayoutSideBar': typeof import("../components/layout/sideBar.vue")['default']
    'LazyModalSearch': typeof import("../components/modalSearch/search.vue")['default']
    'LazyModalSearchNav': typeof import("../components/modalSearch/searchNav.vue")['default']
    'LazyVideoModal': typeof import("../components/videoModal/videoModal.vue")['default']
    'LazyVideoModalForCardsVideoModal': typeof import("../components/videoModalForCards/videoModal.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyAutoComplete': typeof import("primevue/autocomplete")['default']
    'LazyCalendar': typeof import("primevue/calendar")['default']
    'LazyCascadeSelect': typeof import("primevue/cascadeselect")['default']
    'LazyCheckbox': typeof import("primevue/checkbox")['default']
    'LazyChips': typeof import("primevue/chips")['default']
    'LazyColorPicker': typeof import("primevue/colorpicker")['default']
    'LazyDropdown': typeof import("primevue/dropdown")['default']
    'LazyFloatLabel': typeof import("primevue/floatlabel")['default']
    'LazyIconField': typeof import("primevue/iconfield")['default']
    'LazyInputGroup': typeof import("primevue/inputgroup")['default']
    'LazyInputGroupAddon': typeof import("primevue/inputgroupaddon")['default']
    'LazyInputIcon': typeof import("primevue/inputicon")['default']
    'LazyInputMask': typeof import("primevue/inputmask")['default']
    'LazyInputNumber': typeof import("primevue/inputnumber")['default']
    'LazyInputOtp': typeof import("primevue/inputotp")['default']
    'LazyInputSwitch': typeof import("primevue/inputswitch")['default']
    'LazyInputText': typeof import("primevue/inputtext")['default']
    'LazyKnob': typeof import("primevue/knob")['default']
    'LazyListbox': typeof import("primevue/listbox")['default']
    'LazyMultiSelect': typeof import("primevue/multiselect")['default']
    'LazyPassword': typeof import("primevue/password")['default']
    'LazyRadioButton': typeof import("primevue/radiobutton")['default']
    'LazyRating': typeof import("primevue/rating")['default']
    'LazySelectButton': typeof import("primevue/selectbutton")['default']
    'LazySlider': typeof import("primevue/slider")['default']
    'LazyTextarea': typeof import("primevue/textarea")['default']
    'LazyToggleButton': typeof import("primevue/togglebutton")['default']
    'LazyTreeSelect': typeof import("primevue/treeselect")['default']
    'LazyTriStateCheckbox': typeof import("primevue/tristatecheckbox")['default']
    'LazyButton': typeof import("primevue/button")['default']
    'LazyButtonGroup': typeof import("primevue/buttongroup")['default']
    'LazySpeedDial': typeof import("primevue/speeddial")['default']
    'LazySplitButton': typeof import("primevue/splitbutton")['default']
    'LazyColumn': typeof import("primevue/column")['default']
    'LazyRow': typeof import("primevue/row")['default']
    'LazyColumnGroup': typeof import("primevue/columngroup")['default']
    'LazyDataTable': typeof import("primevue/datatable")['default']
    'LazyDataView': typeof import("primevue/dataview")['default']
    'LazyDataViewLayoutOptions': typeof import("primevue/dataviewlayoutoptions")['default']
    'LazyOrderList': typeof import("primevue/orderlist")['default']
    'LazyOrganizationChart': typeof import("primevue/organizationchart")['default']
    'LazyPaginator': typeof import("primevue/paginator")['default']
    'LazyPickList': typeof import("primevue/picklist")['default']
    'LazyTree': typeof import("primevue/tree")['default']
    'LazyTreeTable': typeof import("primevue/treetable")['default']
    'LazyTimeline': typeof import("primevue/timeline")['default']
    'LazyVirtualScroller': typeof import("primevue/virtualscroller")['default']
    'LazyAccordion': typeof import("primevue/accordion")['default']
    'LazyAccordionTab': typeof import("primevue/accordiontab")['default']
    'LazyCard': typeof import("primevue/card")['default']
    'LazyDeferredContent': typeof import("primevue/deferredcontent")['default']
    'LazyDivider': typeof import("primevue/divider")['default']
    'LazyFieldset': typeof import("primevue/fieldset")['default']
    'LazyPanel': typeof import("primevue/panel")['default']
    'LazyScrollPanel': typeof import("primevue/scrollpanel")['default']
    'LazySplitter': typeof import("primevue/splitter")['default']
    'LazySplitterPanel': typeof import("primevue/splitterpanel")['default']
    'LazyStepper': typeof import("primevue/stepper")['default']
    'LazyStepperPanel': typeof import("primevue/stepperpanel")['default']
    'LazyTabView': typeof import("primevue/tabview")['default']
    'LazyTabPanel': typeof import("primevue/tabpanel")['default']
    'LazyToolbar': typeof import("primevue/toolbar")['default']
    'LazyConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'LazyConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'LazyDialog': typeof import("primevue/dialog")['default']
    'LazyDynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'LazyOverlayPanel': typeof import("primevue/overlaypanel")['default']
    'LazySidebar': typeof import("primevue/sidebar")['default']
    'LazyFileUpload': typeof import("primevue/fileupload")['default']
    'LazyBreadcrumb': typeof import("primevue/breadcrumb")['default']
    'LazyContextMenu': typeof import("primevue/contextmenu")['default']
    'LazyDock': typeof import("primevue/dock")['default']
    'LazyMenu': typeof import("primevue/menu")['default']
    'LazyMenubar': typeof import("primevue/menubar")['default']
    'LazyMegaMenu': typeof import("primevue/megamenu")['default']
    'LazyPanelMenu': typeof import("primevue/panelmenu")['default']
    'LazySteps': typeof import("primevue/steps")['default']
    'LazyTabMenu': typeof import("primevue/tabmenu")['default']
    'LazyTieredMenu': typeof import("primevue/tieredmenu")['default']
    'LazyMessage': typeof import("primevue/message")['default']
    'LazyInlineMessage': typeof import("primevue/inlinemessage")['default']
    'LazyToast': typeof import("primevue/toast")['default']
    'LazyCarousel': typeof import("primevue/carousel")['default']
    'LazyGalleria': typeof import("primevue/galleria")['default']
    'LazyImage': typeof import("primevue/image")['default']
    'LazyAvatarGroup': typeof import("primevue/avatargroup")['default']
    'LazyBadge': typeof import("primevue/badge")['default']
    'LazyBlockUI': typeof import("primevue/blockui")['default']
    'LazyChip': typeof import("primevue/chip")['default']
    'LazyInplace': typeof import("primevue/inplace")['default']
    'LazyMeterGroup': typeof import("primevue/metergroup")['default']
    'LazyScrollTop': typeof import("primevue/scrolltop")['default']
    'LazySkeleton': typeof import("primevue/skeleton")['default']
    'LazyProgressBar': typeof import("primevue/progressbar")['default']
    'LazyProgressSpinner': typeof import("primevue/progressspinner")['default']
    'LazyTag': typeof import("primevue/tag")['default']
    'LazyTerminal': typeof import("primevue/terminal")['default']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Banner: typeof import("../components/global/banner.vue")['default']
export const CardsCardShow: typeof import("../components/Cards/cardShow.vue")['default']
export const CardsCardShowTvs: typeof import("../components/Cards/cardShowTvs.vue")['default']
export const HomeMovieCardsDetails: typeof import("../components/HomeMovie/CardsDetails.vue")['default']
export const HomeMovieTopHeader: typeof import("../components/HomeMovie/TopHeader.vue")['default']
export const HomeMovie: typeof import("../components/HomeMovie/movie.vue")['default']
export const SearchAllSearchs: typeof import("../components/Search/allSearchs.vue")['default']
export const ThemeChangeTheme: typeof import("../components/Theme/changeTheme.vue")['default']
export const ToastFaield: typeof import("../components/Toast/toastFaield.vue")['default']
export const ToastSuccess: typeof import("../components/Toast/toastSuccess.vue")['default']
export const TvShowTvshow: typeof import("../components/TvShow/Tvshow.vue")['default']
export const AuthLogin: typeof import("../components/auth/Login.vue")['default']
export const AuthRegister: typeof import("../components/auth/Register.vue")['default']
export const Avatar: typeof import("../components/avatar/avatar.vue")['default']
export const ButtonsCardButtons: typeof import("../components/buttonsCard/buttons.vue")['default']
export const CardloadinHomeCardLoading: typeof import("../components/cardloadinHome/cardLoading.vue")['default']
export const ImageSwiperImages: typeof import("../components/imageSwiper/images.vue")['default']
export const LangDropDown: typeof import("../components/lang/DropDown.vue")['default']
export const LayoutAuthHeaderNav: typeof import("../components/layout/auth/headerNav.vue")['default']
export const LayoutNavBar: typeof import("../components/layout/navBar.vue")['default']
export const LayoutSideBar: typeof import("../components/layout/sideBar.vue")['default']
export const ModalSearch: typeof import("../components/modalSearch/search.vue")['default']
export const ModalSearchNav: typeof import("../components/modalSearch/searchNav.vue")['default']
export const VideoModal: typeof import("../components/videoModal/videoModal.vue")['default']
export const VideoModalForCardsVideoModal: typeof import("../components/videoModalForCards/videoModal.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const AutoComplete: typeof import("primevue/autocomplete")['default']
export const Calendar: typeof import("primevue/calendar")['default']
export const CascadeSelect: typeof import("primevue/cascadeselect")['default']
export const Checkbox: typeof import("primevue/checkbox")['default']
export const Chips: typeof import("primevue/chips")['default']
export const ColorPicker: typeof import("primevue/colorpicker")['default']
export const Dropdown: typeof import("primevue/dropdown")['default']
export const FloatLabel: typeof import("primevue/floatlabel")['default']
export const IconField: typeof import("primevue/iconfield")['default']
export const InputGroup: typeof import("primevue/inputgroup")['default']
export const InputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const InputIcon: typeof import("primevue/inputicon")['default']
export const InputMask: typeof import("primevue/inputmask")['default']
export const InputNumber: typeof import("primevue/inputnumber")['default']
export const InputOtp: typeof import("primevue/inputotp")['default']
export const InputSwitch: typeof import("primevue/inputswitch")['default']
export const InputText: typeof import("primevue/inputtext")['default']
export const Knob: typeof import("primevue/knob")['default']
export const Listbox: typeof import("primevue/listbox")['default']
export const MultiSelect: typeof import("primevue/multiselect")['default']
export const Password: typeof import("primevue/password")['default']
export const RadioButton: typeof import("primevue/radiobutton")['default']
export const Rating: typeof import("primevue/rating")['default']
export const SelectButton: typeof import("primevue/selectbutton")['default']
export const Slider: typeof import("primevue/slider")['default']
export const Textarea: typeof import("primevue/textarea")['default']
export const ToggleButton: typeof import("primevue/togglebutton")['default']
export const TreeSelect: typeof import("primevue/treeselect")['default']
export const TriStateCheckbox: typeof import("primevue/tristatecheckbox")['default']
export const Button: typeof import("primevue/button")['default']
export const ButtonGroup: typeof import("primevue/buttongroup")['default']
export const SpeedDial: typeof import("primevue/speeddial")['default']
export const SplitButton: typeof import("primevue/splitbutton")['default']
export const Column: typeof import("primevue/column")['default']
export const Row: typeof import("primevue/row")['default']
export const ColumnGroup: typeof import("primevue/columngroup")['default']
export const DataTable: typeof import("primevue/datatable")['default']
export const DataView: typeof import("primevue/dataview")['default']
export const DataViewLayoutOptions: typeof import("primevue/dataviewlayoutoptions")['default']
export const OrderList: typeof import("primevue/orderlist")['default']
export const OrganizationChart: typeof import("primevue/organizationchart")['default']
export const Paginator: typeof import("primevue/paginator")['default']
export const PickList: typeof import("primevue/picklist")['default']
export const Tree: typeof import("primevue/tree")['default']
export const TreeTable: typeof import("primevue/treetable")['default']
export const Timeline: typeof import("primevue/timeline")['default']
export const VirtualScroller: typeof import("primevue/virtualscroller")['default']
export const Accordion: typeof import("primevue/accordion")['default']
export const AccordionTab: typeof import("primevue/accordiontab")['default']
export const Card: typeof import("primevue/card")['default']
export const DeferredContent: typeof import("primevue/deferredcontent")['default']
export const Divider: typeof import("primevue/divider")['default']
export const Fieldset: typeof import("primevue/fieldset")['default']
export const Panel: typeof import("primevue/panel")['default']
export const ScrollPanel: typeof import("primevue/scrollpanel")['default']
export const Splitter: typeof import("primevue/splitter")['default']
export const SplitterPanel: typeof import("primevue/splitterpanel")['default']
export const Stepper: typeof import("primevue/stepper")['default']
export const StepperPanel: typeof import("primevue/stepperpanel")['default']
export const TabView: typeof import("primevue/tabview")['default']
export const TabPanel: typeof import("primevue/tabpanel")['default']
export const Toolbar: typeof import("primevue/toolbar")['default']
export const ConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const ConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const Dialog: typeof import("primevue/dialog")['default']
export const DynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const OverlayPanel: typeof import("primevue/overlaypanel")['default']
export const Sidebar: typeof import("primevue/sidebar")['default']
export const FileUpload: typeof import("primevue/fileupload")['default']
export const Breadcrumb: typeof import("primevue/breadcrumb")['default']
export const ContextMenu: typeof import("primevue/contextmenu")['default']
export const Dock: typeof import("primevue/dock")['default']
export const Menu: typeof import("primevue/menu")['default']
export const Menubar: typeof import("primevue/menubar")['default']
export const MegaMenu: typeof import("primevue/megamenu")['default']
export const PanelMenu: typeof import("primevue/panelmenu")['default']
export const Steps: typeof import("primevue/steps")['default']
export const TabMenu: typeof import("primevue/tabmenu")['default']
export const TieredMenu: typeof import("primevue/tieredmenu")['default']
export const Message: typeof import("primevue/message")['default']
export const InlineMessage: typeof import("primevue/inlinemessage")['default']
export const Toast: typeof import("primevue/toast")['default']
export const Carousel: typeof import("primevue/carousel")['default']
export const Galleria: typeof import("primevue/galleria")['default']
export const Image: typeof import("primevue/image")['default']
export const AvatarGroup: typeof import("primevue/avatargroup")['default']
export const Badge: typeof import("primevue/badge")['default']
export const BlockUI: typeof import("primevue/blockui")['default']
export const Chip: typeof import("primevue/chip")['default']
export const Inplace: typeof import("primevue/inplace")['default']
export const MeterGroup: typeof import("primevue/metergroup")['default']
export const ScrollTop: typeof import("primevue/scrolltop")['default']
export const Skeleton: typeof import("primevue/skeleton")['default']
export const ProgressBar: typeof import("primevue/progressbar")['default']
export const ProgressSpinner: typeof import("primevue/progressspinner")['default']
export const Tag: typeof import("primevue/tag")['default']
export const Terminal: typeof import("primevue/terminal")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBanner: typeof import("../components/global/banner.vue")['default']
export const LazyCardsCardShow: typeof import("../components/Cards/cardShow.vue")['default']
export const LazyCardsCardShowTvs: typeof import("../components/Cards/cardShowTvs.vue")['default']
export const LazyHomeMovieCardsDetails: typeof import("../components/HomeMovie/CardsDetails.vue")['default']
export const LazyHomeMovieTopHeader: typeof import("../components/HomeMovie/TopHeader.vue")['default']
export const LazyHomeMovie: typeof import("../components/HomeMovie/movie.vue")['default']
export const LazySearchAllSearchs: typeof import("../components/Search/allSearchs.vue")['default']
export const LazyThemeChangeTheme: typeof import("../components/Theme/changeTheme.vue")['default']
export const LazyToastFaield: typeof import("../components/Toast/toastFaield.vue")['default']
export const LazyToastSuccess: typeof import("../components/Toast/toastSuccess.vue")['default']
export const LazyTvShowTvshow: typeof import("../components/TvShow/Tvshow.vue")['default']
export const LazyAuthLogin: typeof import("../components/auth/Login.vue")['default']
export const LazyAuthRegister: typeof import("../components/auth/Register.vue")['default']
export const LazyAvatar: typeof import("../components/avatar/avatar.vue")['default']
export const LazyButtonsCardButtons: typeof import("../components/buttonsCard/buttons.vue")['default']
export const LazyCardloadinHomeCardLoading: typeof import("../components/cardloadinHome/cardLoading.vue")['default']
export const LazyImageSwiperImages: typeof import("../components/imageSwiper/images.vue")['default']
export const LazyLangDropDown: typeof import("../components/lang/DropDown.vue")['default']
export const LazyLayoutAuthHeaderNav: typeof import("../components/layout/auth/headerNav.vue")['default']
export const LazyLayoutNavBar: typeof import("../components/layout/navBar.vue")['default']
export const LazyLayoutSideBar: typeof import("../components/layout/sideBar.vue")['default']
export const LazyModalSearch: typeof import("../components/modalSearch/search.vue")['default']
export const LazyModalSearchNav: typeof import("../components/modalSearch/searchNav.vue")['default']
export const LazyVideoModal: typeof import("../components/videoModal/videoModal.vue")['default']
export const LazyVideoModalForCardsVideoModal: typeof import("../components/videoModalForCards/videoModal.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyAutoComplete: typeof import("primevue/autocomplete")['default']
export const LazyCalendar: typeof import("primevue/calendar")['default']
export const LazyCascadeSelect: typeof import("primevue/cascadeselect")['default']
export const LazyCheckbox: typeof import("primevue/checkbox")['default']
export const LazyChips: typeof import("primevue/chips")['default']
export const LazyColorPicker: typeof import("primevue/colorpicker")['default']
export const LazyDropdown: typeof import("primevue/dropdown")['default']
export const LazyFloatLabel: typeof import("primevue/floatlabel")['default']
export const LazyIconField: typeof import("primevue/iconfield")['default']
export const LazyInputGroup: typeof import("primevue/inputgroup")['default']
export const LazyInputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const LazyInputIcon: typeof import("primevue/inputicon")['default']
export const LazyInputMask: typeof import("primevue/inputmask")['default']
export const LazyInputNumber: typeof import("primevue/inputnumber")['default']
export const LazyInputOtp: typeof import("primevue/inputotp")['default']
export const LazyInputSwitch: typeof import("primevue/inputswitch")['default']
export const LazyInputText: typeof import("primevue/inputtext")['default']
export const LazyKnob: typeof import("primevue/knob")['default']
export const LazyListbox: typeof import("primevue/listbox")['default']
export const LazyMultiSelect: typeof import("primevue/multiselect")['default']
export const LazyPassword: typeof import("primevue/password")['default']
export const LazyRadioButton: typeof import("primevue/radiobutton")['default']
export const LazyRating: typeof import("primevue/rating")['default']
export const LazySelectButton: typeof import("primevue/selectbutton")['default']
export const LazySlider: typeof import("primevue/slider")['default']
export const LazyTextarea: typeof import("primevue/textarea")['default']
export const LazyToggleButton: typeof import("primevue/togglebutton")['default']
export const LazyTreeSelect: typeof import("primevue/treeselect")['default']
export const LazyTriStateCheckbox: typeof import("primevue/tristatecheckbox")['default']
export const LazyButton: typeof import("primevue/button")['default']
export const LazyButtonGroup: typeof import("primevue/buttongroup")['default']
export const LazySpeedDial: typeof import("primevue/speeddial")['default']
export const LazySplitButton: typeof import("primevue/splitbutton")['default']
export const LazyColumn: typeof import("primevue/column")['default']
export const LazyRow: typeof import("primevue/row")['default']
export const LazyColumnGroup: typeof import("primevue/columngroup")['default']
export const LazyDataTable: typeof import("primevue/datatable")['default']
export const LazyDataView: typeof import("primevue/dataview")['default']
export const LazyDataViewLayoutOptions: typeof import("primevue/dataviewlayoutoptions")['default']
export const LazyOrderList: typeof import("primevue/orderlist")['default']
export const LazyOrganizationChart: typeof import("primevue/organizationchart")['default']
export const LazyPaginator: typeof import("primevue/paginator")['default']
export const LazyPickList: typeof import("primevue/picklist")['default']
export const LazyTree: typeof import("primevue/tree")['default']
export const LazyTreeTable: typeof import("primevue/treetable")['default']
export const LazyTimeline: typeof import("primevue/timeline")['default']
export const LazyVirtualScroller: typeof import("primevue/virtualscroller")['default']
export const LazyAccordion: typeof import("primevue/accordion")['default']
export const LazyAccordionTab: typeof import("primevue/accordiontab")['default']
export const LazyCard: typeof import("primevue/card")['default']
export const LazyDeferredContent: typeof import("primevue/deferredcontent")['default']
export const LazyDivider: typeof import("primevue/divider")['default']
export const LazyFieldset: typeof import("primevue/fieldset")['default']
export const LazyPanel: typeof import("primevue/panel")['default']
export const LazyScrollPanel: typeof import("primevue/scrollpanel")['default']
export const LazySplitter: typeof import("primevue/splitter")['default']
export const LazySplitterPanel: typeof import("primevue/splitterpanel")['default']
export const LazyStepper: typeof import("primevue/stepper")['default']
export const LazyStepperPanel: typeof import("primevue/stepperpanel")['default']
export const LazyTabView: typeof import("primevue/tabview")['default']
export const LazyTabPanel: typeof import("primevue/tabpanel")['default']
export const LazyToolbar: typeof import("primevue/toolbar")['default']
export const LazyConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const LazyConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const LazyDialog: typeof import("primevue/dialog")['default']
export const LazyDynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const LazyOverlayPanel: typeof import("primevue/overlaypanel")['default']
export const LazySidebar: typeof import("primevue/sidebar")['default']
export const LazyFileUpload: typeof import("primevue/fileupload")['default']
export const LazyBreadcrumb: typeof import("primevue/breadcrumb")['default']
export const LazyContextMenu: typeof import("primevue/contextmenu")['default']
export const LazyDock: typeof import("primevue/dock")['default']
export const LazyMenu: typeof import("primevue/menu")['default']
export const LazyMenubar: typeof import("primevue/menubar")['default']
export const LazyMegaMenu: typeof import("primevue/megamenu")['default']
export const LazyPanelMenu: typeof import("primevue/panelmenu")['default']
export const LazySteps: typeof import("primevue/steps")['default']
export const LazyTabMenu: typeof import("primevue/tabmenu")['default']
export const LazyTieredMenu: typeof import("primevue/tieredmenu")['default']
export const LazyMessage: typeof import("primevue/message")['default']
export const LazyInlineMessage: typeof import("primevue/inlinemessage")['default']
export const LazyToast: typeof import("primevue/toast")['default']
export const LazyCarousel: typeof import("primevue/carousel")['default']
export const LazyGalleria: typeof import("primevue/galleria")['default']
export const LazyImage: typeof import("primevue/image")['default']
export const LazyAvatarGroup: typeof import("primevue/avatargroup")['default']
export const LazyBadge: typeof import("primevue/badge")['default']
export const LazyBlockUI: typeof import("primevue/blockui")['default']
export const LazyChip: typeof import("primevue/chip")['default']
export const LazyInplace: typeof import("primevue/inplace")['default']
export const LazyMeterGroup: typeof import("primevue/metergroup")['default']
export const LazyScrollTop: typeof import("primevue/scrolltop")['default']
export const LazySkeleton: typeof import("primevue/skeleton")['default']
export const LazyProgressBar: typeof import("primevue/progressbar")['default']
export const LazyProgressSpinner: typeof import("primevue/progressspinner")['default']
export const LazyTag: typeof import("primevue/tag")['default']
export const LazyTerminal: typeof import("primevue/terminal")['default']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
