
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'SearchAllActors': typeof import("../components/Search/allActors.vue")['default']
    'SearchAllMovie': typeof import("../components/Search/allMovie.vue")['default']
    'SearchAllTvs': typeof import("../components/Search/allTvs.vue")['default']
    'ToastFaield': typeof import("../components/Toast/toastFaield.vue")['default']
    'ToastSuccess': typeof import("../components/Toast/toastSuccess.vue")['default']
    'AuthLogin': typeof import("../components/auth/Login.vue")['default']
    'AuthRegister': typeof import("../components/auth/Register.vue")['default']
    'Avatar': typeof import("../components/avatar/avatar.vue")['default']
    'ImageSwiperImages': typeof import("../components/imageSwiper/images.vue")['default']
    'LangDropDown': typeof import("../components/lang/DropDown.vue")['default']
    'LayoutAuthHeaderNav': typeof import("../components/layout/auth/headerNav.vue")['default']
    'LayoutNavBar': typeof import("../components/layout/navBar.vue")['default']
    'LayoutSideBar': typeof import("../components/layout/sideBar.vue")['default']
    'ModalSearch': typeof import("../components/modalSearch/search.vue")['default']
    'ModalSearchNav': typeof import("../components/modalSearch/searchNav.vue")['default']
    'VideoModal': typeof import("../components/videoModal/videoModal.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazySearchAllActors': typeof import("../components/Search/allActors.vue")['default']
    'LazySearchAllMovie': typeof import("../components/Search/allMovie.vue")['default']
    'LazySearchAllTvs': typeof import("../components/Search/allTvs.vue")['default']
    'LazyToastFaield': typeof import("../components/Toast/toastFaield.vue")['default']
    'LazyToastSuccess': typeof import("../components/Toast/toastSuccess.vue")['default']
    'LazyAuthLogin': typeof import("../components/auth/Login.vue")['default']
    'LazyAuthRegister': typeof import("../components/auth/Register.vue")['default']
    'LazyAvatar': typeof import("../components/avatar/avatar.vue")['default']
    'LazyImageSwiperImages': typeof import("../components/imageSwiper/images.vue")['default']
    'LazyLangDropDown': typeof import("../components/lang/DropDown.vue")['default']
    'LazyLayoutAuthHeaderNav': typeof import("../components/layout/auth/headerNav.vue")['default']
    'LazyLayoutNavBar': typeof import("../components/layout/navBar.vue")['default']
    'LazyLayoutSideBar': typeof import("../components/layout/sideBar.vue")['default']
    'LazyModalSearch': typeof import("../components/modalSearch/search.vue")['default']
    'LazyModalSearchNav': typeof import("../components/modalSearch/searchNav.vue")['default']
    'LazyVideoModal': typeof import("../components/videoModal/videoModal.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const SearchAllActors: typeof import("../components/Search/allActors.vue")['default']
export const SearchAllMovie: typeof import("../components/Search/allMovie.vue")['default']
export const SearchAllTvs: typeof import("../components/Search/allTvs.vue")['default']
export const ToastFaield: typeof import("../components/Toast/toastFaield.vue")['default']
export const ToastSuccess: typeof import("../components/Toast/toastSuccess.vue")['default']
export const AuthLogin: typeof import("../components/auth/Login.vue")['default']
export const AuthRegister: typeof import("../components/auth/Register.vue")['default']
export const Avatar: typeof import("../components/avatar/avatar.vue")['default']
export const ImageSwiperImages: typeof import("../components/imageSwiper/images.vue")['default']
export const LangDropDown: typeof import("../components/lang/DropDown.vue")['default']
export const LayoutAuthHeaderNav: typeof import("../components/layout/auth/headerNav.vue")['default']
export const LayoutNavBar: typeof import("../components/layout/navBar.vue")['default']
export const LayoutSideBar: typeof import("../components/layout/sideBar.vue")['default']
export const ModalSearch: typeof import("../components/modalSearch/search.vue")['default']
export const ModalSearchNav: typeof import("../components/modalSearch/searchNav.vue")['default']
export const VideoModal: typeof import("../components/videoModal/videoModal.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazySearchAllActors: typeof import("../components/Search/allActors.vue")['default']
export const LazySearchAllMovie: typeof import("../components/Search/allMovie.vue")['default']
export const LazySearchAllTvs: typeof import("../components/Search/allTvs.vue")['default']
export const LazyToastFaield: typeof import("../components/Toast/toastFaield.vue")['default']
export const LazyToastSuccess: typeof import("../components/Toast/toastSuccess.vue")['default']
export const LazyAuthLogin: typeof import("../components/auth/Login.vue")['default']
export const LazyAuthRegister: typeof import("../components/auth/Register.vue")['default']
export const LazyAvatar: typeof import("../components/avatar/avatar.vue")['default']
export const LazyImageSwiperImages: typeof import("../components/imageSwiper/images.vue")['default']
export const LazyLangDropDown: typeof import("../components/lang/DropDown.vue")['default']
export const LazyLayoutAuthHeaderNav: typeof import("../components/layout/auth/headerNav.vue")['default']
export const LazyLayoutNavBar: typeof import("../components/layout/navBar.vue")['default']
export const LazyLayoutSideBar: typeof import("../components/layout/sideBar.vue")['default']
export const LazyModalSearch: typeof import("../components/modalSearch/search.vue")['default']
export const LazyModalSearchNav: typeof import("../components/modalSearch/searchNav.vue")['default']
export const LazyVideoModal: typeof import("../components/videoModal/videoModal.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
