// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/20/2024, 4:59:37 PM
const configMerger = require("E:/Projects/Nuxt/leader-movie/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["E:/Projects/Nuxt/leader-movie/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Projects/Nuxt/leader-movie/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Projects/Nuxt/leader-movie/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Projects/Nuxt/leader-movie/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Projects/Nuxt/leader-movie/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Projects/Nuxt/leader-movie/plugins/**/*.{js,ts,mjs}","E:/Projects/Nuxt/leader-movie/composables/**/*.{js,ts,mjs}","E:/Projects/Nuxt/leader-movie/utils/**/*.{js,ts,mjs}","E:/Projects/Nuxt/leader-movie/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/Projects/Nuxt/leader-movie/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/Projects/Nuxt/leader-movie/app.config.{js,ts,mjs}"] }));

module.exports = config
